rules:
  import/extensions: # NOTE: extends Airbnb rule
    - error
    - ignorePackages
    - js: never
      mjs: never
      jsx: never
      ts: never
      tsx: never
  import/no-extraneous-dependencies: # NOTE: extends Airbnb rule
    - error
    - devDependencies:
        - 'test/**' # tape, common npm pattern
        - 'tests/**' # also common npm pattern
        - 'spec/**' # mocha, rspec-like pattern
        - '**/__tests__/**' # jest pattern
        - '**/__mocks__/**' # jest pattern
        - 'test.{js,jsx,ts,tsx}' # repos with a single test file
        - 'test-*.{js,jsx,ts,tsx}' # repos with multiple top-level test files
        - '**/*{.,_}{test,spec}.{js,jsx,ts,tsx}' # tests where the extension or filename suffix denotes that it is a test
        - '**/jest.config.js' # jest config
        - '**/jest.setup.js' # jest setup
        - '**/vue.config.js' # vue-cli config
        - '**/webpack.config.js' # webpack config
        - '**/webpack.config.*.js' # webpack config
        - '**/rollup.config.js' # rollup config
        - '**/rollup.config.*.js' # rollup config
        - '**/gulpfile.js' # gulp config
        - '**/gulpfile.*.js' # gulp config
        - '**/Gruntfile{,.js}' # grunt config
        - '**/protractor.conf.js' # protractor config
        - '**/protractor.conf.*.js' # protractor config
        - '**/karma.conf.js' # karma config
      optionalDependencies: false

overrides:
  - files: ['src/types/**/*.ts']
    rules:
      import/prefer-default-export: off
