---
parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: module

settings:
  import/resolver:
    ts:
      alwaysTryTypes: true
  import/extensions: # NOTE: extends Airbnb rule
    - '.js'
    - '.jsx'
    - '.ts'
    - '.tsx'
    - '.mjs'
