---
env:
  node: true
  jest/globals: true

parser: babel-eslint

extends:
  - "@acmecryptocorp"
  - "@acmecryptocorp/eslint-config/flow"
  - "plugin:jest/recommended"
  - "plugin:jest/style"

plugins:
  - jest
