rules:
  curly:
    - error
    - all
  lines-between-class-members:
    - error
    - always
    - exceptAfterSingleLine: true
  prefer-arrow-callback: error
  prefer-destructuring: "off"

overrides:
  - files:
      - "*.flow.js"
      - "*.types.js"
    rules:
      no-use-before-define: "off"
