rules:
  curly:
    - error
    - all
  lines-between-class-members:
    - error
    - always
    - exceptAfterSingleLine: true
  prefer-arrow-callback: error
  prefer-destructuring: 'off'
  quotes:
    - error
    - single
    - avoidEscape: true
      allowTemplateLiterals: false
