---
plugins:
  - import

rules:
  import/group-exports: off
  import/order:
    - error
    - groups:
        - builtin
        - - external
          - internal
        - parent
        - - index
          - sibling
      newlines-between: always
