---
plugins:
  - import

rules:
  import/group-exports: error
  import/order:
    - error
    - groups:
        - builtin
        - - external
          - internal
        - parent
        - - index
          - sibling
      newlines-between: always

overrides:
  - files:
      - '*.types.js'
      - '*.flow.js'
    rules:
      import/group-exports: off
