---
plugins:
  - promise

rules:
  promise/always-return: error
  promise/avoid-new: 'off'
  promise/catch-or-return: error
  promise/no-callback-in-promise: warn
  promise/no-native: 'off'
  promise/no-nesting: error
  promise/no-new-statics: error
  promise/no-promise-in-callback: warn
  promise/no-return-in-finally: warn
  promise/no-return-wrap: error
  promise/param-names: error
  promise/prefer-await-to-callbacks: 'off' # NOTE: bad realisation
  promise/prefer-await-to-then: warn
  promise/valid-params: 'off' # NOTE: flow does this
