---
plugins:
  - sort-class-members

rules:
  sort-class-members/sort-class-members:
    - error
    - accessorPairPositioning: getThenSet
      order:
        - '[static-properties]'
        - '[properties]'
        - constructor
        - '[static-methods]' # NOTE: setter-getter pairs
          # - '[getters]' # NOTE: doesn't seem to work
          # - '[setters]'
        - '[accessor-pairs]'
        - '[arrow-function-properties]'
        - '[methods]'
        - '[everything-else]'
      stopAfterFirstProblem: true
