---
plugins:
  - unicorn

rules:
  unicorn/catch-error-name: error
  unicorn/custom-error-definition: error
  unicorn/error-message: error
  unicorn/escape-case: "off"
  unicorn/expiring-todo-comments: off
  unicorn/explicit-length-check: error
  unicorn/filename-case: "off" # NOTE: redundant -- eslint-plugin-filenames
  unicorn/import-index: "off" # NOTE: redundant -- eslint-plugin-import
  unicorn/new-for-builtins: error
  unicorn/no-abusive-eslint-disable: "off" # NOTE: redundant -- eslint-plugin-eslint-comments
  unicorn/no-array-instanceof: error
  unicorn/no-console-spaces: "off"
  unicorn/no-fn-reference-in-iterator: off
  unicorn/no-for-loop: "off" # NOTE: redundant -- eslint-plugin-no-loops
  unicorn/no-hex-escape: error
  unicorn/no-keyword-prefix: off
  unicorn/no-nested-ternary: off
  unicorn/no-new-buffer: error
  unicorn/no-process-exit: "off"
  unicorn/no-unreadable-array-destructuring: warn
  unicorn/no-unsafe-regex: warn
  unicorn/no-unused-properties: warn
  unicorn/no-zero-fractions: error
  unicorn/number-literal-case: error
  unicorn/prefer-add-event-listener: warn
  unicorn/prefer-dataset: off
  unicorn/prefer-event-key: "off"
  unicorn/prefer-exponentiation-operator: "off"
  unicorn/prefer-flat-map: error
  unicorn/prefer-includes: error
  unicorn/prefer-node-append: "off"
  unicorn/prefer-node-remove: "off"
  unicorn/prefer-query-selector: "off"
  unicorn/prefer-spread: error
  unicorn/prefer-starts-ends-with: error
  unicorn/prefer-text-content: "off"
  unicorn/prefer-type-error: error
  unicorn/prevent-abbreveations: off
  unicorn/regex-shorthand: "off" # NOTE: redundant -- eslint-plugin-optimize-regex
  unicorn/throw-new-error: error
