---
plugins:
  - unicorn

rules:
  unicorn/catch-error-name: error
  unicorn/explicit-length-check: error
  unicorn/filename-case: off # NOTE: redundant -- eslint-plugin-filenames
  unicorn/no-abusive-eslint-disable: off # NOTE: redundant -- eslint-plugin-eslint-comments
  unicorn/no-process-exit: off # COMBAK: possibly redundant TODO: discuss
  unicorn/throw-new-error: error
  unicorn/number-literal-case: error
  unicorn/escape-case: off
  unicorn/no-array-instanceof: error
  unicorn/no-new-buffer: error
  unicorn/no-hex-escape: error
  unicorn/custom-error-definition: error
  unicorn/prefer-starts-ends-with: error
  unicorn/prefer-type-error: error
  unicorn/no-fn-reference-in-iterator: warn
  unicorn/import-index: off # NOTE: redundant -- eslint-plugin-import
  unicorn/new-for-builtins: error
  unicorn/regex-shorthand: off # NOTE: redundant -- eslint-plugin-optimize-regex
  unicorn/prefer-spread: error
  unicorn/error-message: error
  unicorn/no-unsafe-regex: warn
  unicorn/prefer-add-event-listener: warn
  unicorn/prefer-exponentiation-operator: off
  unicorn/no-console-spaces: off
  unicorn/no-unreadable-array-destructuring: warn
  unicorn/no-unused-properties: warn
  unicorn/prefer-node-append: off
  unicorn/prefer-query-selector: off
  unicorn/prefer-node-remove: off
  unicorn/prefer-text-content: off
  unicorn/no-for-loop: off # NOTE: redundant -- eslint-plugin-no-loops
  unicorn/no-zero-fractions: error
  unicorn/prefer-event-key: off
  unicorn/prefer-flat-map: error
  unicorn/prefer-includes: error
