---
plugins:
  - "@acmecryptocorp/eslint-plugin"

rules:
  "@acmecryptocorp/require-exact-object-type": error
  "@acmecryptocorp/require-variable-type": error
  "@acmecryptocorp/type-export-filename": error
