---
plugins:
  - '@acmecryptocorp/eslint-plugin'

rules:
  '@acmecryptocorp/require-exact-object-type': error
  '@acmecryptocorp/require-variable-type': off
  '@acmecryptocorp/type-export-filename': error
